# Generated by Django 4.2.13 on 2024-05-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholicDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Алкогольные напитки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='title')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.alcoholicdrink')),
            ],
        ),
    ]
