# Generated by Django 4.2.13 on 2024-05-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_cocktail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='bar.alcoholicdrink'),
        ),
    ]
